### ISSUE TITLE
missing field 'isPercent' in interface Format

### ISSUE THREAD

**Issue by cbtum** [WebDataRocks/ng-webdatarocks#2]
I am using "ng-webdatarocks": "^1.4.6" and "webdatarocks": "^1.4.6".
Sorry, this issue seems to be a problem in webdatarocks itself, but I can't find this repository here.

The `isPercent`-Formatting mentioned [in the docs](https://www.webdatarocks.com/doc/number-formatting/) seems to be missing in this interface. Hence, I was not able to set the predefined layout that I wanted. After adding this field in the downloaded `webdatarocks.d.ts`, I was able to predefine the desired layout

    interface Format {
        name?: string;
        thousandsSeparator?: string;
        decimalSeparator?: string;
        decimalPlaces?: number;
        maxDecimalPlaces?: number;
        maxSymbols?: number;
        currencySymbol?: string;
        currencySymbolAlign?: string;
        nullValue?: string;
        infinityValue?: string;
        divideByZeroValue?: string;
        textAlign?: string;
        **isPercent?: boolean;**
    }

**Comment by solja484** [comment]
Hello!

Thank you for reporting this issue.

We will fix it in the next WDR update. 
Before that, kindly suggest adding the `isPercent` to webdatarocks.d.ts as a workaround.

Kind regards,
Solomiia
