### ISSUE TITLE
Update for Angular 16 and IVY support

### ISSUE THREAD

**Issue by b1rigu** [WebDataRocks/ng-webdatarocks#3]
Is there any chance that this library will be updated to Angular 16?. Because I really liked this library and we can't use it because we have migrated to Angular 16. I tried to update it manually but didn't really know how

**Comment by b1rigu** [comment]
I have been tackling it all day and made an Ivy compatible Angular 12+ wrapper for webdatarocks here: https://github.com/b1rigu/ngx-webdatarocks
It would be much appreciated if you guys add this wrapper to the official website angular integration as it can help many people

**Comment by maksymkaD** [comment]
Hello, @b1rigu

Thank you for implementing the Ivy-compatible wrapper for WebDataRocks. Your efforts have greatly enhanced our project.
We will work on including the Ivy-compatible version of WDR in our official distribution.

**Comment by maksymkaD** [comment]
Hello, @b1rigu 

We are glad to announce that we have added the Ivy-compatible WebDataRocks module to our official distribution. It is now available to download from npm: https://www.npmjs.com/package/@webdatarocks/ngx-webdatarocks

Our team kindly requests that you remove your package from the npm registry to avoid any confusion among users.

**Comment by b1rigu** [comment]
Okkay
