### ISSUE TITLE
In the webdatarocks (type: 'flat') Need to freeze or pin the first column for horizontal scroll.

### ISSUE THREAD

**Issue by gangamaism** [WebDataRocks/ng-webdatarocks#4]
In the webdatarocks (type: 'flat') Need to freeze or pin the first column for horizontal scroll.

Not able to freeze the first column by applying the custom CSS in **onCustomizeCell**. Can anyone please help to freeze or pin the first column from horizontal scroll in webdatarocks (type-flat)

<img width="583" alt="WEBDATAROCKS FLAT TYPE " src="https://github.com/WebDataRocks/ng-webdatarocks/assets/127426820/f158f8cf-1916-402f-9fde-0abae39173a7">

**Comment by maksymkaD** [comment]
Hello,

Thank you for your question.
Currently, we have no available solutions for freezing columns. 

Best Regards,

**Comment by gangamaism** [comment]
Okay, Thank you for reply.
